// SPDX-License-Identifier: BSD-2-Clause
using ClassicUO.Game.Data;
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace ClassicUO.Resources
{
    /// <summary>Display-only translations. Never changes protocol IDs, macro keys or saved names.</summary>
    internal static class UiLocalization
    {
        public static bool IsChinese => ResGumps.Culture?.Name == "zh-CN";
        private static readonly Dictionary<string, string> Chinese = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Add a new tab"] = "新增标签页",
            ["Agility"] = "敏捷术",
            ["Air Elemental"] = "气元素",
            ["Alchemy"] = "炼金术",
            ["Alliance"] = "联盟",
            ["AllowedToDraw"] = "允许显示",
            ["Ally"] = "盟友",
            ["AlphaHue"] = "透明度与色调",
            ["Amount"] = "数量",
            ["Anatomy"] = "解剖学",
            ["Animal Form"] = "动物形态",
            ["Animal Lore"] = "动物学",
            ["Animal Taming"] = "驯兽",
            ["Animate Dead"] = "亡者复生",
            ["Animated Weapon"] = "活化武器",
            ["Anticipate Hit"] = "预判攻击",
            ["Arcane Circle"] = "秘法之环",
            ["Arcane Empowerment"] = "秘法强化",
            ["Arch Cure"] = "群体解毒术",
            ["Arch Protection"] = "群体防护术",
            ["Archery"] = "弓术",
            ["Arms Lore"] = "武器学",
            ["Attunement"] = "调和",
            ["AvgZ"] = "平均高度",
            ["Backstab"] = "背刺",
            ["Base"] = "基础",
            ["Begging"] = "乞讨",
            ["Berserk"] = "狂怒",
            ["Blacksmithing"] = "锻造",
            ["Blacksmithy"] = "锻造",
            ["Blade Spirits"] = "剑刃精魂",
            ["Bless"] = "祝福术",
            ["Blood Oath"] = "血之誓约",
            ["Boarding"] = "寄养",
            ["Bodyguard"] = "护卫",
            ["Bombard"] = "轰击",
            ["Bowcraft/Fletching"] = "弓箭制作",
            ["Bushido"] = "武士道",
            ["Called Shot"] = "精确射击",
            ["Camping"] = "野营",
            ["Cap"] = "上限",
            ["Carpentry"] = "木工",
            ["Cartography"] = "制图",
            ["Chain Lightning"] = "连锁闪电",
            ["Character Selection"] = "选择角色",
            ["Chivalry"] = "骑士精神",
            ["Choose a Trade for Your Character"] = "为你的角色选择职业",
            ["Cleanse by Fire"] = "火焰净化",
            ["Cleansing Winds"] = "净化之风",
            ["Click here"] = "点击此处",
            ["Client"] = "客户端",
            ["Close Wounds"] = "愈合伤口",
            ["Clumsy"] = "笨拙术",
            ["Combat Training"] = "战斗训练",
            ["Command"] = "指令",
            ["Command Undead"] = "号令亡灵",
            ["Conduit"] = "导流",
            ["Confidence"] = "自信",
            ["Consecrate Weapon"] = "神圣武器",
            ["Container"] = "容器",
            ["Cooking"] = "烹饪",
            ["Corpse Skin"] = "尸皮术",
            ["Corpses"] = "尸体",
            ["Counter Attack"] = "反击",
            ["Create Food"] = "造食术",
            ["Criminal"] = "罪犯",
            ["Cunning"] = "灵巧术",
            ["Cure"] = "解毒术",
            ["Curse"] = "诅咒术",
            ["Curse Weapon"] = "诅咒武器",
            ["Data"] = "数据",
            ["Deadly Aim"] = "致命瞄准",
            ["Death Ray"] = "死亡射线",
            ["Death Strike"] = "致命一击",
            ["Despair"] = "绝望",
            ["Detecting Hidden"] = "侦测隐藏",
            ["Difficult to Track"] = "难以追踪",
            ["Direction"] = "方向",
            ["Discordance"] = "不和谐",
            ["Dispel"] = "驱散术",
            ["Dispel Evil"] = "驱散邪恶",
            ["Dispel Field"] = "驱散力场",
            ["Distance"] = "距离",
            ["Divine Fury"] = "神圣之怒",
            ["Dryad Allure"] = "树精魅惑",
            ["Eagle Strike"] = "鹰击",
            ["Earth Elemental"] = "土元素",
            ["Earthquake"] = "地震术",
            ["Eighth Circle"] = "第八环",
            ["Elemental Fury"] = "元素之怒",
            ["Emote"] = "表情",
            ["Enchant"] = "附魔",
            ["Enchanted Summoning"] = "强化召唤",
            ["Encoded"] = "编码消息",
            ["Enemy"] = "敌人",
            ["Enemy of One"] = "唯一之敌",
            ["Energy Bolt"] = "能量箭",
            ["Energy Field"] = "能量场",
            ["Energy Vortex"] = "能量漩涡",
            ["Enter a tab name"] = "输入标签页名称",
            ["Essence of Wind"] = "风之精华",
            ["Ethereal Burst"] = "以太爆发",
            ["Ethereal Voyage"] = "虚空航行",
            ["Evaluating Intelligence"] = "评估智力",
            ["Evasion"] = "闪避",
            ["Evil Omen"] = "邪恶预兆",
            ["Exorcism"] = "驱魔",
            ["Explosion"] = "爆炸术",
            ["Facet"] = "世界",
            ["Feeblemind"] = "弱智术",
            ["Felucca"] = "菲卢卡",
            ["Fencing"] = "刺击",
            ["Fifth Circle"] = "第五环",
            ["Fire Elemental"] = "火元素",
            ["Fire Field"] = "火墙术",
            ["Fireball"] = "火球术",
            ["First Circle"] = "第一环",
            ["Fishing"] = "钓鱼",
            ["Fists of Fury"] = "怒拳",
            ["Flags"] = "标记",
            ["Flamestrike"] = "烈焰打击",
            ["Flaming Shot"] = "烈焰射击",
            ["Flying"] = "飞行",
            ["Focus"] = "专注",
            ["Focus Attack"] = "专注攻击",
            ["Focused Eye"] = "专注之眼",
            ["Forensic Evaluation"] = "鉴识",
            ["Fourth Circle"] = "第四环",
            ["GameEffect"] = "游戏特效",
            ["Gate Travel"] = "传送门",
            ["Gift of Life"] = "生命之赐",
            ["Gift of Renewal"] = "复苏之赐",
            ["Global Chat"] = "公共聊天",
            ["Graphics"] = "图形",
            ["Gray"] = "灰名",
            ["Greater Heal"] = "强效治疗术",
            ["Guild"] = "公会",
            ["Hail Storm"] = "冰雹风暴",
            ["Harm"] = "伤害术",
            ["Heal"] = "治疗术",
            ["Healing"] = "治疗",
            ["Healing Stone"] = "治疗石",
            ["Heighten Senses"] = "感官强化",
            ["Herding"] = "放牧",
            ["Hiding"] = "隐藏",
            ["Holy Fist"] = "神圣之拳",
            ["Holy Light"] = "圣光",
            ["Honorable Execution"] = "荣誉处决",
            ["Horrific Beast"] = "恐怖野兽",
            ["House not legal, not committing!"] = "房屋结构不合法，无法提交！",
            ["Hue"] = "颜色",
            ["Icon"] = "图标",
            ["Ilshenar"] = "伊尔谢纳",
            ["Imbuing"] = "附魔",
            ["Immolating Weapon"] = "献祭武器",
            ["Incognito"] = "易容术",
            ["Info"] = "信息",
            ["Infused with Magic"] = "魔力充盈",
            ["Injected Strike"] = "注毒攻击",
            ["Innocent"] = "无辜者",
            ["Inscription"] = "铭文",
            ["Inspire"] = "鼓舞",
            ["Intuition"] = "直觉",
            ["Invigorate"] = "振奋",
            ["Invisibility"] = "隐身术",
            ["Invulnerable"] = "无敌",
            ["IsCoins"] = "金币",
            ["IsDead"] = "死亡状态",
            ["IsDrivingABoat"] = "驾船状态",
            ["IsFlat"] = "平面",
            ["IsMounted"] = "骑乘状态",
            ["IsMovable"] = "可移动",
            ["IsMulti"] = "组合物件",
            ["IsRenamable"] = "可重命名",
            ["IsVegetation"] = "植被",
            ["Item Identification"] = "物品鉴定",
            ["Items"] = "物品",
            ["Jack of All Trades"] = "博学多才",
            ["Ki Attack"] = "气击",
            ["Knockout"] = "击昏",
            ["Knowledge of Nature"] = "自然知识",
            ["Label"] = "标签",
            ["Layer"] = "装备栏",
            ["Lich Form"] = "巫妖形态",
            ["Lightning"] = "闪电术",
            ["Lightning Strike"] = "闪电一击",
            ["Limit3Spell(Sphere)"] = "法术限制（Sphere）",
            ["Lockpicking"] = "开锁",
            ["Lumberjacking"] = "伐木",
            ["Mace Fighting"] = "锤术",
            ["Magery"] = "魔法",
            ["Magic Arrow"] = "魔法箭",
            ["Magic Lock"] = "魔法锁",
            ["Magic Reflection"] = "魔法反射",
            ["Magic Trap"] = "魔法陷阱",
            ["Magic Untrap"] = "解除魔法陷阱",
            ["Malas"] = "马拉斯",
            ["Mana"] = "法力",
            ["Mana Drain"] = "法力吸取",
            ["Mana Shield"] = "法力护盾",
            ["Mana Vampire"] = "法力吸血",
            ["Mark"] = "标记术",
            ["Mass Curse"] = "群体诅咒术",
            ["Mass Dispel"] = "群体驱散术",
            ["Mass Sleep"] = "群体沉睡",
            ["Master Artisan"] = "工匠大师",
            ["Meditation"] = "冥想",
            ["Meteor Swarm"] = "流星雨",
            ["MinZ"] = "最低高度",
            ["Mind Blast"] = "心灵冲击",
            ["Mind Rot"] = "心智腐蚀",
            ["Mining"] = "采矿",
            ["Mirror Image"] = "镜像",
            ["Momentum Strike"] = "冲势打击",
            ["MultiGraphic"] = "组合图形",
            ["Murderer"] = "杀人犯",
            ["Musicianship"] = "音乐",
            ["Mystic Insight"] = "神秘洞察",
            ["Mystic Weapon"] = "神秘武器",
            ["Mysticism"] = "神秘术",
            ["Name"] = "名称",
            ["Nature's Fury"] = "自然之怒",
            ["Necromancy"] = "死灵术",
            ["Nether Blast"] = "虚空冲击",
            ["Nether Bolt"] = "虚空之箭",
            ["Nether Cyclone"] = "虚空旋风",
            ["Night Sight"] = "夜视术",
            ["Ninjitsu"] = "忍术",
            ["Noble Sacrifice"] = "崇高牺牲",
            ["NormalBottom"] = "下侧法线",
            ["NormalLeft"] = "左侧法线",
            ["NormalRight"] = "右侧法线",
            ["NormalTop"] = "上侧法线",
            ["Notoriety"] = "善恶状态",
            ["Onslaught"] = "猛攻",
            ["Pain Spike"] = "痛苦尖刺",
            ["Paralyze"] = "麻痹术",
            ["Paralyze Field"] = "麻痹力场",
            ["Parrying"] = "格挡",
            ["Party"] = "队伍",
            ["Peacemaking"] = "安抚",
            ["Perception"] = "感知",
            ["Perseverance"] = "坚韧",
            ["Pierce"] = "穿刺",
            ["Playing The Odds"] = "把握胜机",
            ["Please wait, I'm making the map file..."] = "正在生成地图，请稍候……",
            ["Poison"] = "毒术",
            ["Poison Field"] = "毒墙术",
            ["Poison Strike"] = "毒击",
            ["Poisoning"] = "下毒",
            ["Polymorph"] = "变形术",
            ["Position"] = "位置",
            ["Potency"] = "毒性强化",
            ["Price"] = "价格",
            ["PriorityZ"] = "高度优先级",
            ["Protection"] = "防护术",
            ["Provocation"] = "挑衅",
            ["Purge Magic"] = "净化魔法",
            ["Race"] = "种族",
            ["Rampage"] = "狂暴",
            ["Reactive Armor"] = "反应护甲",
            ["Reaper Form"] = "死神形态",
            ["Recall"] = "回城术",
            ["Regular"] = "普通",
            ["Rejuvenate"] = "复苏",
            ["Remove Curse"] = "移除诅咒",
            ["Remove Trap"] = "解除陷阱",
            ["Resilience"] = "韧性",
            ["Resisting Spells"] = "魔法抗性",
            ["Resurrection"] = "复活术",
            ["Reveal"] = "显形术",
            ["Rising Colossus"] = "巨像崛起",
            ["Sacred Journey"] = "神圣之旅",
            ["Second Circle"] = "第二环",
            ["Serial"] = "序列号",
            ["Seventh Circle"] = "第七环",
            ["Shadow"] = "跟踪",
            ["Shadowjump"] = "影跃",
            ["Shield Bash"] = "盾击",
            ["Sixth Circle"] = "第六环",
            ["Sleep"] = "沉睡",
            ["Snooping"] = "窥探",
            ["SpeedMode"] = "速度模式",
            ["Spell"] = "法术",
            ["Spell Plague"] = "法术瘟疫",
            ["Spell Trigger"] = "法术触发",
            ["Spellweaving"] = "编织法术",
            ["Spirit Speak"] = "通灵",
            ["Stagger"] = "踉跄",
            ["Stamina"] = "耐力",
            ["State"] = "状态",
            ["Stealing"] = "偷窃",
            ["Stealth"] = "潜行",
            ["Stone Form"] = "石化形态",
            ["Strangle"] = "绞杀",
            ["Strength"] = "力量",
            ["Strong Back"] = "强健背脊",
            ["Summon Creature"] = "召唤生物",
            ["Summon Daemon"] = "召唤恶魔",
            ["Summon Familiar"] = "召唤使魔",
            ["Summon Fey"] = "召唤妖精",
            ["Summon Fiend"] = "召唤恶魔",
            ["Summon Reaper"] = "召唤收割者",
            ["Surprise Attack"] = "突袭",
            ["Swordsmanship"] = "剑术",
            ["System"] = "系统",
            ["Tactics"] = "战术",
            ["Tailoring"] = "裁缝",
            ["Taste Identification"] = "味觉鉴定",
            ["Telekinesis"] = "隔空取物",
            ["Teleport"] = "瞬移术",
            ["Ter Mur"] = "泰尔穆尔",
            ["Stygian Abyss"] = "冥河深渊",
            ["Third Circle"] = "第三环",
            ["Throwing"] = "投掷",
            ["Thrust"] = "突刺",
            ["Thunderstorm"] = "雷暴",
            ["Tinkering"] = "工艺",
            ["Title"] = "标题",
            ["Tokuno"] = "德野",
            ["Tolerance"] = "耐受",
            ["Tough"] = "强壮",
            ["Toughness"] = "坚韧体魄",
            ["Tracking"] = "追踪",
            ["Trammel"] = "特拉梅尔",
            ["Tribulation"] = "苦难",
            ["UO Store"] = "商城",
            ["Unlock"] = "开锁术",
            ["Value"] = "当前",
            ["Vampiric Embrace"] = "吸血之拥",
            ["Vengeful Spirit"] = "复仇之魂",
            ["Veterinary"] = "兽医",
            ["Wall of Stone"] = "石墙术",
            ["Warcry"] = "战吼",
            ["Warrior's Gifts"] = "战士恩赐",
            ["Water Elemental"] = "水元素",
            ["Weaken"] = "虚弱术",
            ["Whisper"] = "低语",
            ["Whispering"] = "低语",
            ["White Tiger Form"] = "白虎形态",
            ["Wildfire"] = "野火",
            ["Wisdom"] = "智慧",
            ["Wither"] = "凋零",
            ["Word of Death"] = "死亡之言",
            ["Workhorse"] = "勤劳",
            ["Wraith Form"] = "幽灵形态",
            ["Wrestling"] = "摔跤",
            ["X Delete Tab"] = "删除标签页",
            ["YOffsets"] = "纵向偏移",
            ["Yell"] = "大喊",
            ["a corpse"] = "尸体",
            ["time out"] = "超时",
            ["Britannia"] = "不列颠尼亚",
            ["Britain"] = "不列颠",
            ["Trinsic"] = "特林西克",
            ["Minoc"] = "米诺克",
            ["Vesper"] = "维斯珀",
            ["Yew"] = "紫杉",
            ["Moonglow"] = "月光城",
            ["Magincia"] = "马金西亚",
            ["Jhelom"] = "杰洛姆",
            ["Skara Brae"] = "斯卡拉布雷",
            ["Cove"] = "海湾镇",
            ["Ocllo"] = "奥克罗",
            ["Nujel'm"] = "努杰姆",
            ["Serpent's Hold"] = "蛇之要塞",
            ["Buccaneer's Den"] = "海盗巢穴",
            ["New Haven"] = "新港",
            ["Haven"] = "避风港",
            ["Wind"] = "风之城",
            ["Papua"] = "帕普亚",
            ["Delucia"] = "德卢西亚",
            ["Luna"] = "月亮城",
            ["Umbra"] = "暗影城",
            ["Zento"] = "禅都",
            ["Bowcraft / Fletching"] = "弓箭制作",
            ["RemoveTrap"] = "解除陷阱",
            ["Eval Intelligence"] = "评估智力",
            ["Item ID"] = "物品鉴定",
            ["Enticement"] = "不和谐",
            ["Disarm"] = "解除陷阱",
            ["None"] = "无",
            ["MSC_NONE"] = "无",
            ["Walk"] = "行走",
            ["WarPeace"] = "切换战斗状态",
            ["Paste"] = "粘贴",
            ["Open"] = "打开",
            ["Close"] = "关闭",
            ["Minimize"] = "最小化",
            ["Maximize"] = "最大化",
            ["OpenDoor"] = "开门",
            ["UseSkill"] = "使用技能",
            ["LastSkill"] = "上次技能",
            ["CastSpell"] = "施法",
            ["LastSpell"] = "上次法术",
            ["LastObject"] = "上次物品",
            ["Bow"] = "鞠躬",
            ["Salute"] = "敬礼",
            ["QuitGame"] = "退出游戏",
            ["AllNames"] = "显示所有名称",
            ["LastTarget"] = "上次目标",
            ["TargetSelf"] = "以自己为目标",
            ["ArmDisarm"] = "装备或卸下武器",
            ["WaitForTarget"] = "等待目标",
            ["TargetNext"] = "下个目标",
            ["AttackLast"] = "攻击上次目标",
            ["Delay"] = "延时",
            ["CircleTrans"] = "圆形透明区域",
            ["CloseGump"] = "关闭窗口",
            ["AlwaysRun"] = "总是跑步",
            ["SaveDesktop"] = "保存界面布局",
            ["KillGumpOpen"] = "关闭光标所在窗口",
            ["PrimaryAbility"] = "主要武器技能",
            ["SecondaryAbility"] = "次要武器技能",
            ["EquipLastWeapon"] = "装备上次武器",
            ["SetUpdateRange"] = "设置视野范围",
            ["ModifyUpdateRange"] = "调整视野范围",
            ["IncreaseUpdateRange"] = "增加视野范围",
            ["DecreaseUpdateRange"] = "减少视野范围",
            ["MaxUpdateRange"] = "最大视野范围",
            ["MinUpdateRange"] = "最小视野范围",
            ["DefaultUpdateRange"] = "默认视野范围",
            ["EnableRangeColor"] = "启用范围颜色",
            ["DisableRangeColor"] = "禁用范围颜色",
            ["ToggleRangeColor"] = "切换范围颜色",
            ["InvokeVirtue"] = "使用美德",
            ["SelectNext"] = "选择下一个",
            ["SelectPrevious"] = "选择上一个",
            ["SelectNearest"] = "选择最近目标",
            ["AttackSelectedTarget"] = "攻击所选目标",
            ["UseSelectedTarget"] = "使用所选目标",
            ["CurrentTarget"] = "当前目标",
            ["TargetSystemOnOff"] = "切换目标系统",
            ["ToggleBuffIconGump"] = "切换状态效果窗口",
            ["BandageSelf"] = "为自己包扎",
            ["BandageTarget"] = "为目标包扎",
            ["ToggleGargoyleFly"] = "切换石像鬼飞行",
            ["ToggleChatVisibility"] = "切换聊天显示",
            ["INVALID"] = "无效",
            ["Aura"] = "光环",
            ["AuraOnOff"] = "切换光环",
            ["Grab"] = "拾取",
            ["SetGrabBag"] = "设置拾取背包",
            ["NamesOnOff"] = "切换名称显示",
            ["UseItemInHand"] = "使用手持物品",
            ["UsePotion"] = "使用药水",
            ["CloseAllHealthBars"] = "关闭所有生命条",
            ["RazorMacro"] = "Razor 宏",
            ["ToggleDrawRoofs"] = "切换屋顶显示",
            ["ToggleTreeStumps"] = "切换树桩显示",
            ["ToggleVegetation"] = "切换植被显示",
            ["ToggleCaveTiles"] = "切换洞穴地砖",
            ["CloseInactiveHealthBars"] = "关闭无效生命条",
            ["CloseCorpses"] = "关闭尸体窗口",
            ["UseObject"] = "使用物品",
            ["LookAtMouse"] = "查看光标位置",
            ["UseCounterBarSlot"] = "使用计数栏物品",
            ["NW"] = "西北",
            ["N"] = "北",
            ["NE"] = "东北",
            ["E"] = "东",
            ["SE"] = "东南",
            ["S"] = "南",
            ["SW"] = "西南",
            ["W"] = "西",
            ["Configuration"] = "设置",
            ["MageSpellbook"] = "魔法书",
            ["Overview"] = "概览",
            ["WorldMap"] = "世界地图",
            ["PartyManifest"] = "队伍成员",
            ["PartyChat"] = "队伍聊天",
            ["NecroSpellbook"] = "死灵法术书",
            ["PaladinSpellbook"] = "骑士法术书",
            ["CombatBook"] = "战斗技能书",
            ["BushidoSpellbook"] = "武士道技能书",
            ["NinjitsuSpellbook"] = "忍术技能书",
            ["SpellWeavingSpellbook"] = "织法术书",
            ["QuestLog"] = "任务日志",
            ["MysticismSpellbook"] = "神秘法术书",
            ["RacialAbilitiesBook"] = "种族能力书",
            ["BardSpellbook"] = "吟游诗人技能书",
            ["DetectingHidden"] = "探测隐藏",
            ["EvaluatingIntelligence"] = "评估智力",
            ["ForensicEvaluation"] = "法医鉴定",
            ["ItemIdentification"] = "物品鉴定",
            ["TasteIdentification"] = "味觉鉴定",
            ["LeftHand"] = "左手",
            ["RightHand"] = "右手",
            ["DispellField"] = "驱散力场",
            ["SummonFamilar"] = "召唤使魔",
            ["CleanceByFire"] = "烈火净化",
            ["HonorableExecution"] = "荣誉处决",
            ["Zoom"] = "缩放",
            ["Say"] = "说话",
            ["Paperdoll"] = "角色面板",
            ["Status"] = "状态",
            ["Journal"] = "日志",
            ["Skills"] = "技能",
            ["Chat"] = "聊天",
            ["Backpack"] = "背包",
            ["Mail"] = "邮件",
            ["Honor"] = "荣誉",
            ["Sacrifice"] = "牺牲",
            ["Valor"] = "英勇",
            ["WallOfStone"] = "石墙术",
            ["FlameStrike"] = "烈焰冲击",
            ["EnemyOfOne"] = "宿敌",
            ["LightingStrike"] = "闪电突击",
            ["SurpriceAttack"] = "突袭",
            ["GiftOfRenewal"] = "复苏之恩",
            ["NaturesFury"] = "自然之怒",
            ["EssenceOfWind"] = "风之精华",
            ["WordOfDeath"] = "死亡之言",
            ["GiftOfLife"] = "生命之恩",
            ["ArcaneEmpowermen"] = "奥术强化",
            ["Hostile"] = "敌对目标",
            ["Follower"] = "随从",
            ["Object"] = "物品",
            ["Mobile"] = "生物",
            ["MscTotalCount"] = "总数",
            ["INVALID_0"] = "无效",
            ["INVALID_1"] = "无效",
            ["INVALID_2"] = "无效",
            ["INVALID_3"] = "无效",
            ["ConfusionBlastPotion"] = "混乱爆破药水",
            ["CurePotion"] = "解毒药水",
            ["AgilityPotion"] = "敏捷药水",
            ["StrengthPotion"] = "力量药水",
            ["PoisonPotion"] = "毒药",
            ["RefreshPotion"] = "精力药水",
            ["HealPotion"] = "治疗药水",
            ["ExplosionPotion"] = "爆炸药水",
            ["DefaultZoom"] = "默认缩放",
            ["ZoomIn"] = "放大",
            ["ZoomOut"] = "缩小",
            ["BestHealPotion"] = "最佳治疗药水",
            ["BestCurePotion"] = "最佳解毒药水",
            ["BestRefreshPotion"] = "最佳精力药水",
            ["BestStrengthPotion"] = "最佳力量药水",
            ["BestAgiPotion"] = "最佳敏捷药水",
            ["BestExplosionPotion"] = "最佳爆炸药水",
            ["BestConflagPotion"] = "最佳燃烧药水",
            ["EnchantedApple"] = "魔法苹果",
            ["PetalsOfTrinsic"] = "特林西克花瓣",
            ["OrangePetals"] = "橙色花瓣",
            ["TrappedBox"] = "陷阱盒",
            ["SmokeBomb"] = "烟雾弹",
            ["HealStone"] = "治疗石",
            ["SpellStone"] = "法术石",
            ["LookForwards"] = "向前看",
            ["LookBackwards"] = "向后看",
            ["Helmet"] = "头盔",
            ["Earrings"] = "耳环",
            ["Necklace"] = "项链",
            ["Ring"] = "戒指",
            ["Bracelet"] = "手镯",
            ["Tunic"] = "上衣",
            ["OneHanded"] = "单手",
            ["TwoHanded"] = "双手",
            ["Talisman"] = "护符",
            ["Robe"] = "长袍",
            ["Gloves"] = "手套",
            ["Pants"] = "裤子",
            ["Arms"] = "手臂",
            ["Cloak"] = "披风",
            ["Shoes"] = "鞋子",
            ["Shutdown"] = "服务器已关闭",
            ["ConnectionReset"] = "连接已重置",
            ["TimedOut"] = "连接超时",
            ["ConnectionRefused"] = "连接被拒绝",
            ["HostUnreachable"] = "无法访问服务器",
            ["NetworkUnreachable"] = "网络不可用",
            ["OperationAborted"] = "连接已中止",
            ["NotConnected"] = "未连接",
            ["ConnectionAborted"] = "连接已中断",
            ["SocketError"] = "网络错误",
            ["Miscellaneous"] = "杂项",
            ["Combat"] = "战斗",
            ["Trade Skills"] = "生产技能",
            ["Magic"] = "魔法",
            ["Wilderness"] = "野外生存",
            ["Thieving"] = "盗贼技能",
            ["Bard"] = "吟游诗人",
        };

        static UiLocalization()
        {
            // Macro enum names omit spaces; translate their captions without changing enum values.
            foreach (var entry in new List<KeyValuePair<string, string>>(Chinese))
            {
                string alias = entry.Key.Replace(" ", "").Replace("/", "");
                if (!Chinese.ContainsKey(alias)) Chinese.Add(alias, entry.Value);
            }
        }

        private static readonly Dictionary<string, string> Ranks = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Neophyte"] = "初学者",
            ["Novice"] = "新手",
            ["Apprentice"] = "学徒",
            ["Journeyman"] = "熟练",
            ["Expert"] = "专家",
            ["Adept"] = "精通",
            ["Master"] = "大师",
            ["Grandmaster"] = "宗师",
            ["Elder"] = "长老",
            ["Legendary"] = "传奇",
            ["Tatsujin"] = "达人",
            ["Shinobi"] = "上忍",
            ["Kengo"] = "剑豪",
            ["Ka-ge"] = "影",
        };

        private static readonly Dictionary<string, string> SkillTitles = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Alchemist"] = "炼金师",
            ["Biologist"] = "生物学家",
            ["Naturalist"] = "博物学家",
            ["Merchant"] = "商人",
            ["Weapon Master"] = "武器大师",
            ["Duelist"] = "决斗家",
            ["Beggar"] = "乞丐",
            ["Blacksmith"] = "铁匠",
            ["Bowyer"] = "制弓师",
            ["Pacifier"] = "安抚者",
            ["Explorer"] = "探险家",
            ["Carpenter"] = "木匠",
            ["Cartographer"] = "制图师",
            ["Chef"] = "厨师",
            ["Scout"] = "斥候",
            ["Demoralizer"] = "扰乱者",
            ["Scholar"] = "学者",
            ["Healer"] = "治疗师",
            ["Fisherman"] = "渔夫",
            ["Forensic Evaluation"] = "法医鉴定",
            ["Detective"] = "侦探",
            ["Shepherd"] = "牧羊人",
            ["Shade"] = "潜藏者",
            ["Rouser"] = "煽动者",
            ["Scribe"] = "抄写员",
            ["Infiltrator"] = "潜入者",
            ["Mage"] = "法师",
            ["Warder"] = "守护者",
            ["Tactician"] = "战术家",
            ["Spy"] = "间谍",
            ["Bard"] = "吟游诗人",
            ["Assassin"] = "刺客",
            ["Archer"] = "弓箭手",
            ["Medium"] = "灵媒",
            ["Pickpocket"] = "扒手",
            ["Tailor"] = "裁缝",
            ["Tamer"] = "驯兽师",
            ["Praegustator"] = "品鉴师",
            ["Tinker"] = "工匠",
            ["Ranger"] = "游侠",
            ["Veterinarian"] = "兽医",
            ["Swordsman"] = "剑士",
            ["Armsman"] = "武者",
            ["Fencer"] = "击剑士",
            ["Wrestler"] = "摔跤手",
            ["Lumberjack"] = "伐木工",
            ["Miner"] = "矿工",
            ["Stoic"] = "冥想者",
            ["Rogue"] = "潜行者",
            ["Trap Specialist"] = "陷阱专家",
            ["Necromancer"] = "死灵法师",
            ["Driven"] = "专注者",
            ["Paladin"] = "骑士",
            ["Samurai"] = "武士",
            ["Ninja"] = "忍者",
            ["Arcanist"] = "奥术师",
            ["Mystic"] = "神秘法师",
            ["Artificer"] = "魔法工匠",
            ["Bladeweaver"] = "投刃师",
            ["Fisherwoman"] = "渔夫",
            ["Swordswoman"] = "剑士",
            ["Armswoman"] = "武者",
        };

        private static readonly Dictionary<string, string> NpcTitles = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["the Holy Mage"] = "神圣法师",
            ["the Keeper of Chivalry"] = "骑士精神守护者",
            ["the Monk"] = "修士",
            ["the alchemist"] = "炼金师",
            ["the animal trainer"] = "驯兽师",
            ["the architect"] = "建筑师",
            ["the armorer"] = "盔甲商",
            ["the baker"] = "面包师",
            ["the banker"] = "银行家",
            ["the bard"] = "吟游诗人",
            ["the barkeeper"] = "酒保",
            ["the beekeeper"] = "养蜂人",
            ["the blacksmith"] = "铁匠",
            ["the bowyer"] = "弓匠",
            ["the butcher"] = "屠夫",
            ["the carpenter"] = "木匠",
            ["the cobbler"] = "鞋匠",
            ["the cook"] = "厨师",
            ["the farmer"] = "农夫",
            ["the fisher"] = "渔夫",
            ["the furtrader"] = "毛皮商",
            ["the golem crafter"] = "魔像工匠",
            ["the gypsy maiden"] = "吉卜赛少女",
            ["the hair stylist"] = "发型师",
            ["the hairstylist"] = "发型师",
            ["the herbalist"] = "草药师",
            ["the innkeeper"] = "旅店老板",
            ["the iron worker"] = "铁器工匠",
            ["the jeweler"] = "珠宝商",
            ["the leather worker"] = "皮革工匠",
            ["the mage"] = "法师",
            ["the mapmaker"] = "制图师",
            ["the miller"] = "磨坊主",
            ["the miner"] = "矿工",
            ["the provisioner"] = "杂货商",
            ["the rancher"] = "牧场主",
            ["the ranger"] = "游侠",
            ["the real estate broker"] = "房产经纪人",
            ["the scribe"] = "抄写员",
            ["the shipwright"] = "造船师",
            ["the stone crafter"] = "石匠",
            ["the tailor"] = "裁缝",
            ["the tanner"] = "制革师",
            ["the tavern keeper"] = "酒馆老板",
            ["the thief"] = "盗贼",
            ["the tinker"] = "工艺师",
            ["the vagabond"] = "流浪者",
            ["the variety dealer"] = "百货商",
            ["the vet"] = "兽医",
            ["the waiter"] = "侍者",
            ["the weaponsmith"] = "武器匠",
            ["the weaver"] = "织工",
        };

        public static string PaperdollTitle(string text)
        {
            if (!IsChinese || string.IsNullOrEmpty(text)) return text;
            // ModernUO appends vendor titles with a space; player skill titles use a comma.
            int npcSeparator = text.LastIndexOf(" the ", StringComparison.OrdinalIgnoreCase);
            if (npcSeparator > 0 && NpcTitles.TryGetValue(text.Substring(npcSeparator + 1), out string npcTitle))
                return text.Substring(0, npcSeparator).TrimEnd(',') + "，" + npcTitle;
            int separator = text.LastIndexOf(", ", StringComparison.Ordinal);
            if (separator < 0) return text;
            string suffix = text.Substring(separator + 2);
            if (NpcTitles.TryGetValue(suffix, out string profession))
                return text.Substring(0, separator) + "，" + profession;
            foreach (var rank in Ranks)
            {
                string prefix = rank.Key + " ";
                if (suffix.StartsWith(prefix, StringComparison.Ordinal) &&
                    SkillTitles.TryGetValue(suffix.Substring(prefix.Length), out string title))
                    return text.Substring(0, separator) + "，" + rank.Value + title;
            }
            return text;
        }

        // Place-name translation belongs only to map labels, never player or guild identities.
        private static readonly HashSet<string> MapPlaces = new HashSet<string>(StringComparer.Ordinal)
        {
            "Britannia", "Britain", "Trinsic", "Minoc", "Vesper", "Yew", "Moonglow",
            "Magincia", "Jhelom", "Skara Brae", "Cove", "Ocllo", "Nujel'm",
            "Serpent's Hold", "Buccaneer's Den", "New Haven", "Haven", "Wind",
            "Papua", "Delucia", "Luna", "Umbra", "Zento", "Felucca", "Trammel",
            "Ilshenar", "Malas", "Tokuno", "Ter Mur", "Stygian Abyss"
        };

        public static string MapPlaceName(string text, bool userDefined = false) =>
            !userDefined && text != null && MapPlaces.Contains(text) ? Translate(text) : text;

        public static string SkillGroupName(string text)
        {
            if (IsChinese) return Translate(text);
            // Profiles created in Chinese may already contain translated default group names.
            return text switch
            {
                "杂项" => "Miscellaneous", "战斗" => "Combat", "生产技能" => "Trade Skills",
                "魔法" => "Magic", "野外生存" => "Wilderness", "盗贼技能" => "Thieving",
                "吟游诗人" => "Bard", _ => text
            };
        }

        public static string GraphicText(ushort graphic) => !IsChinese ? null : graphic switch
        {
            0x0834 => "技能",
            0x0836 => "点按钮使用技能\n无按钮则在场景中使用",
            _ => null
        };

        public static string ArtCaption(ushort graphic)
        {
            if (!IsChinese) return null;
            return graphic switch
            {
                0x07ef => "帮助", 0x07d6 => "设置", 0x07d9 => "退出",
                0x083a => "新建分组",
                0x159d => "新建", 0x159a => "删除",
                0x093b => "时区", 0x093e => "负载", 0x0941 => "连接",
                0x07dc => "日志", 0x57b5 => "任务", 0x07df => "技能",
                0x57b2 => "公会", 0x07e5 => "和平", 0x07e8 => "战斗", 0x07eb => "状态",
                _ => null
            };
        }

        private static readonly Dictionary<string, string> SystemMessages = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Target can not be revived this way."] = "无法用这种方式复活目标。",
            ["That familiar has not yet been defined."] = "尚未定义这种使魔。",
            ["The other gate no longer exists."] = "另一端的传送门已不存在。",
            ["They already have nightsight."] = "目标已经拥有夜视效果。",
            ["You already have nightsight."] = "你已经拥有夜视效果。",
            ["You cannot cast this spell when in sudden death."] = "骤死阶段无法施放此法术。",
            ["This spell is temporarily disabled."] = "此法术暂时无法使用。",
            ["You may not steal in this area."] = "此区域禁止偷窃。",
            ["You may not use peacemaking in this area."] = "此区域无法使用安抚。",
            ["You may not use peacemaking there."] = "无法在那里使用安抚。"
        };

        public static string SystemMessage(string text, MessageType type, bool serverSystem = false)
        {
            if (!IsChinese || string.IsNullOrEmpty(text) ||
                !(type == MessageType.System || type == MessageType.Regular && serverSystem)) return text;
            return SystemMessages.TryGetValue(text, out string translated) ? translated : text;
        }

        public static string ChatChannelName(string name) =>
            IsChinese && name == "General" ? "综合" : name;

        public static bool RequiresUnicode(string text)
        {
            if (text == null) return false;
            foreach (char character in text) if (character > 0xFF) return true;
            return false;
        }

        public static string Translate(string text)
        {
            if (!IsChinese || string.IsNullOrEmpty(text)) return text;
            return Chinese.TryGetValue(text, out string translated) ? translated : text;
        }

        public static string Html(string text)
        {
            if (!IsChinese || string.IsNullOrEmpty(text)) return text;
            return Regex.Replace(text, @"(?<=>)[^<>]+(?=<)|^[^<>]+(?=<)|(?<=>)[^<>]+$|^[^<>]+$", match =>
            {
                string value = match.Value;
                string trimmed = value.Trim();
                string translated = Translate(trimmed);
                int offset = value.IndexOf(trimmed, StringComparison.Ordinal);
                return trimmed.Length == 0 || translated == trimmed ? value : value.Substring(0, offset) + translated + value.Substring(offset + trimmed.Length);
            });
        }

        public static string Format(string english, string chinese, params object[] args) =>
            string.Format(IsChinese ? chinese : english, args);
    }
}
